[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apscheduler>=3.11.0",
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "flask-socketio>=5.5.1",
    "jsonschema>=4.25.0",
    "simplejson>=3.20.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.7",
]
