name: Test

on:
  push:
    branches-ignore:
      - master

jobs:
  test-backend:
    runs-on: ubuntu-latest
    env:
      backend-directory: ./backend

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: |
        uv sync --dev
      working-directory: ${{ env.backend-directory }}

    - name: Lint with ruff
      run: |
        uv run ruff check .
      working-directory: ${{ env.backend-directory }}

    - name: Format check with ruff
      run: |
        uv run ruff format --check .
      working-directory: ${{ env.backend-directory }}

    - name: Type check with mypy
      run: |
        uv run mypy .
      working-directory: ${{ env.backend-directory }}

    - name: Test with pytest
      run: |
        uv run pytest tests/ -v
      working-directory: ${{ env.backend-directory }}

    - name: Test coverage
      run: |
        uv run coverage run -m pytest tests/
        uv run coverage report
      working-directory: ${{ env.backend-directory }}

  test-frontend:
    runs-on: ubuntu-latest
    env:
      frontend-directory: ./frontend

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: |
        npm ci
      working-directory: ${{ env.frontend-directory }}

    - name: Type check
      run: |
        npm run build
      working-directory: ${{ env.frontend-directory }}

    - name: Lint
      run: |
        npm run lint
      working-directory: ${{ env.frontend-directory }}

    - name: Run tests
      run: |
        npm run test -- --run
      working-directory: ${{ env.frontend-directory }}

  test:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    steps:
      - run: echo "All tests passed"
